2022-12-20 00:05:29,842 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:05:29,844 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:05:29,844 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 00:05:29,847 - ERROR - ProfileManager.py - Line: 274 - ** Error: Exception caught at _update_profile!
2022-12-20 00:05:29,848 - ERROR - ProfileManager.py - Line: 275 - ** Error: Traceback (most recent call last):
  File "C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\Settings\ProfileManager.py", line 272, in _remove_node
    root.remve(child)
AttributeError: 'lxml.etree._Element' object has no attribute 'remve'

2022-12-20 00:06:14,947 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:06:14,947 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:06:14,947 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 00:06:14,948 - DEBUG - ProfileManager.py - Line: 48 - Creating backups for new profile
2022-12-20 00:06:14,948 - INFO - ProfileManager.py - Line: 343 - copy C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\settings.xml -> C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\settings.TestProfile04.xml
2022-12-20 00:06:14,950 - INFO - ProfileManager.py - Line: 343 - copy C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\Db\Actors.csv -> C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\Db\Actors.TestProfile04.csv
2022-12-20 00:06:14,951 - INFO - ProfileManager.py - Line: 343 - copy C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\Db\SceneOrder.csv -> C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\Db\SceneOrder.TestProfile04.csv
2022-12-20 00:06:14,953 - INFO - ProfileManager.py - Line: 343 - copy C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\Db\Comments.csv -> C:\Users\Usuario\PycharmProjects\CKsQuestDialogManager\App\Db\Comments.TestProfile04.csv
2022-12-20 00:06:32,306 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:06:32,307 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:06:32,307 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 00:14:49,217 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:14:49,217 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:14:49,217 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 00:16:15,377 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:16:15,377 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:16:15,377 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 00:16:40,326 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:16:40,327 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:16:40,327 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 00:17:52,964 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 00:17:52,964 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 00:17:52,964 - INFO - Logger.py - Line: 49 - -----------------------------------
2022-12-20 23:59:12,709 - INFO - Logger.py - Line: 47 - -----------------------------------
2022-12-20 23:59:12,709 - INFO - Logger.py - Line: 48 - Log system successfully initialised
2022-12-20 23:59:12,710 - INFO - Logger.py - Line: 49 - -----------------------------------
